- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: rd 
  remote_user: root
  vars:
      redash_version: 3.0.0.b3134
  tasks:

    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python-pip
        - python-dev
        - nginx
        - curl
        - build-essential
        - pwgen
        - libffi-dev 
        - libssl-dev
        - default-libmysqlclient-dev
        - libpq-dev
        - freetds-dev
        - libsasl2-dev
        - postgresql
        - redis-server
        - supervisor
        - sudo

    - name: Create base redash directory
      file:
          path: /opt/redash/current
          state: directory

    - name: Save environment settings
      copy:
          src: env
          dest: /opt/redash/current/.env

    - name: Generate cookie secret for site
      shell: COOKIE_SECRET=$(pwgen -1s 32) && echo "export REDASH_COOKIE_SECRET=$COOKIE_SECRET" >> /opt/redash/current/.env

    - name: Get redash source
      get_url:
          url: "https://s3.amazonaws.com/redash-releases/redash.{{ redash_version }}.tar.gz"
          dest: /tmp/redash.tar.gz

    - name: Unarchieve redash
      unarchive:
          src:  /tmp/redash.tar.gz
          dest: /opt/redash/current
          remote_src: yes

    - name: Set file permissions
      file: 
        dest: /opt/redash/current
        owner: root
        group: root
        recurse: yes

    - name: Set pip conf file
      copy:
          src: pip.conf
          dest: /etc/pip.conf

    - name: Install pip module
      pip:
          name: setproctitle

    - name: Install python dependencies
      pip:
          requirements: "{{ item }}"
      with_items:
          - /opt/redash/current/requirements.txt
          - /opt/redash/current/requirements_all_ds.txt

    - name: Configure Postgresql
      copy:
          src: pg_hba.conf
          dest: /etc/postgresql/9.6/main/pg_hba.conf

    - name: Restart postgresql
      service:
          name: postgresql
          state: restarted

    - name: Create Database User
      become: yes
      become_user: postgres
      postgresql_user:
          name: root
          state: present

    - name: Create Database
      postgresql_db:
          name: redash
          owner: root

    - name: Configure Postgresql
      copy:
          src: pg_hba.conf
          dest: /etc/postgresql/9.6/main/pg_hba.conf

    - name: Setup tables
      django_manage:
          app_path: /opt/redash/current
          command: "database create_tables"

    - name: Create Error log directory
      file:
          path: /var/log/redash
          state: directory

    - name: Setup supervisor conf file
      copy:
          src: supervisord.conf
          dest: /etc/supervisor/conf.d/redash.conf

    - name: Restart supervisor service
      service:
          name: supervisor
          state: restarted

    - name: Copy redash server file
      copy:
          src: nginx_redash_site
          dest: /etc/nginx/sites-available/redash

    - name: Enable redash server
      file:
          remote_src: true
          src: /etc/nginx/sites-available/redash
          dest: /etc/nginx/sites-enabled/redash
          state: link

    - name: Remove default site
      file:
          path: /etc/nginx/sites-enabled/default
          state: absent

    - name: Restart nginx
      service:
          name: nginx
          state: restarted

